<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
      <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    
	<? $linkedtitle = $this->driver->getLinkedTitle(); if (!empty($linkedtitle)): ?>
    <h3 property="name">
	    <? foreach($linkedtitle as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?></h3>
    <? endif; ?>
  
    <h3 property="name"><? $title = rtrim(($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())," / ")?><?=$this->escapeHtml($title)?></h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
	  <? $linkedsummary = $this->driver->getLinkedDescription(); if (!empty($linkedsummary)): ?>
        <? foreach ($linkedsummary as $field): ?><?= $this->escapeHtml($field)?><br/>
		<? endforeach; ?>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>
		
	<? // CUSTOM HTML ADDED FOR SOAS LIBRARY
       // @author Simon Barron <sb174@soas.ac.uk>
	   // Taken from ./templates/RecordTabs/holdingsils.phtml
    ?>
	
<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $openUrl = $this->driver->openURLActive('holdings') ? $this->driver->getOpenURL() : false;
    $offlineMode = $this->ils()->getOfflineMode();
    // Account for replace_other_urls setting
    $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
?>

<div class="holdings">
	
	<? $journalholdings = $this->driver->getJournalHoldings(); if (!empty($journalholdings)): ?>
	<table class="table table-responsive" summary="<?=$this->transEsc('Journal holdings details')?>">
        <tr valign="top">
		<? $shelflocation = $this->driver->getShelfLocation(); if (!empty($shelflocation)): ?>
			<? foreach ($shelflocation as $location): ?>
			<td><a href="http://www.soas.ac.uk/library/using/finding/location/"><?=$this->escapeHtml($location)?></a></td>
			<? endforeach; ?>
		<? endif; ?>
          <? $classmark = $this->driver->getClassmark(); if(!empty($classmark)): ?>
             <td><a href="/Alphabrowse/Home?source=callnumber&from=<?=$this->escapeHtml($classmark)?>"><?= $this->escapeHtml($classmark)?></a><br/></td>
          <? endif; ?>
         <? endif; ?>
          <td><? foreach ($journalholdings as $field): ?><?= $this->escapeHtml($field)?><br/><? endforeach; ?></td>
        </tr>
	</table>

  <? if (!empty($urls) || $openUrl): ?>
  <table class="table table-responsive" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc("Internet")?>">
  <tr>
  <? $accessnote = $this->driver->getNote(); if (!empty($accessnote)): ?>
    <? foreach ($accessnote as $field): ?>
	
 	<?if (stripos($field, 'SOAS') !== false): ?>
	   <td><i><?= $this->escapeHtml($field)?></i>
		</td>
      	<? endif; ?>
    <? endforeach; ?>
  <? endif; ?>
  
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <tr><td><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a></td></tr>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrl): ?><?=$this->openUrl($openUrl);?><? endif; ?>
  </table>
<? endif; ?>

	<? foreach ($holdings as $holding): ?>
		<table class="table table-responsive" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
		<? if (!empty($holding['summary'])): ?>
		<tr>
    <th><?=$this->transEsc("Volume Holdings")?>: </th>
    <td>
      <? foreach ($holding['summary'] as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['notes'])): ?>
  <tr>
    <th><?=$this->transEsc("Notes")?>: </th>
    <td>
      <? foreach ($holding['notes'] as $data): ?>
        <?=$this->escapeHtml($data)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? foreach ($holding['items'] as $row): ?>
    <? if (strpos($row['status'],'ONORDER') !== false):?>
       <td><?=$this->transEsc("On order")?></td>
    <? endif; ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? $checkStorageRetrievalRequest = (isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <!--<th class="hidden-xs"><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>-->
        <td class="hidden-xs">
        <? if ($row['holdings']): ?> <?=$this->escapeHtml($row['holdings'])?>
        <? endif; ?>
        </td>
		<? if (stripos($holding['location'], 'Main') !== false): ?>
			<? $shelflocation = $this->driver->getShelfLocation(); if (!empty($shelflocation)): ?>
			<? foreach ($shelflocation as $location): ?>
			<td><a href="http://www.soas.ac.uk/library/using/finding/location/"><?=$this->escapeHtml($location)?></a></td>
			<? endforeach; ?>
			<? else: ?>
				<td>
				<a href="http://www.soas.ac.uk/library/using/finding/location/"><?=$this->transEsc($holding['location'])?></a>
				</td>
			<? endif; ?>
		<? elseif (stripos($holding['location'], 'DAGEN') !== false): ?>
			<td>
			<a href="http://www.soas.ac.uk/library/using/finding/location/">Dagenham Store</a>
			</td>
		<? elseif (stripos($holding['location'], 'EGHAM') !== false): ?>
                        <td>
                        <a href="http://www.soas.ac.uk/library/using/finding/location/">Egham Store</a>
                        </td>
		<? endif; ?>
        <td>
        <strong class="hidden-xs"><?=$this->transEsc("Call Number")?>:</strong> <? if ($row['callnumber']): ?> <!--<strong class="hidden-xs"><?=$this->transEsc("Call Number")?>:</strong>--> <a href="/Alphabrowse/Home?source=callnumber&from=<?=$this->escapeHtml($row['callnumberDisplay'])?>"><?=$this->escapeHtml($row['callnumberDisplay'])?></a> <?=$this->escapeHtml($row['enumeration'])?>
        <? endif; ?>
        </td>

        <td class="hidden-xs">
		<script>
			$(document).ready(function(){
			$("#tooltip-ex a").tooltip({
			placement : 'top'
			});
			});
		</script>
        <? if ($row['type']): ?>
			<? if (stripos($row['type'], 'LONG LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Anyone with SOAS Library membership can borrow this item type")?>"><?=$this->escapeHtml($row['type'])?></a>
			</div>
			<? elseif (stripos($row['type'], 'ONE WEEK LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only SOAS staff and students can borrow this item type")?>"><?=$this->escapeHtml($row['type'])?></a>
			</div>
			<? elseif (stripos($row['type'], 'THREE DAY LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only SOAS staff and students can borrow this item type")?>"><?=$this->escapeHtml($row['type'])?></a>
			</div>
			<? elseif (stripos($item['type'], 'SHORT') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only SOAS staff and students can borrow this item type")?>"><?=$this->escapeHtml($item['type'])?></a>
			</div>
			<? elseif (stripos($row['type'], 'REFERENCE ONLY') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only for use in the library")?>"><?=$this->escapeHtml($row['type'])?></a>
			</div>
			<? else: ?>
			<?=$this->escapeHtml($row['type'])?>
			<? endif; ?>
        <? endif; ?>
	</td>

        <td>
        <?=$this->escapeHtml($row['collection'])?>
        </td>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="text-success"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/InStock" /></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <a style="display:inline-block" class="<?=$check ? 'checkRequest ' : ''?>inlineblock modal-link placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"><i class="icon-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?>modal-link placeStorageRetrievalRequest" href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="icon-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="text-danger"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
			  <? if (stripos($row['status'], 'On loan') !== false): ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> modal-link inlineblock placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>
			  <? endif; ?>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtml($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtml($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtml($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>

  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>
</div>

	<?// END OF CUSTOM HTML //?>
	
    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
	
	  <? $statement = $this->driver->getStatement(); if (!empty($statement)): ?>
      <tr>
        <th><?=$this->transEsc('Full Title')?>: </th>
        <td>
          <? foreach($statement as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
		  <? $linkedstatement = $this->driver->getLinkedStatement(); if (!empty($linkedstatement)): ?>
          <? foreach($linkedstatement as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
		<? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $alttitle = $this->driver->getAltTitle(); if (!empty($alttitle)): ?>
      <tr>
        <th><?=$this->transEsc('Alternative Titles')?>: </th>
        <td>
          <? foreach($alttitle as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
		  <? $linkedalttitle = $this->driver->getLinkedTitleAlt(); if (!empty($linkedalttitle)): ?>
			<? foreach($linkedalttitle as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
			<? endforeach; ?>
		  <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td property="author">
					
		<a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a>
		<br />
		<? $linkedauthor = $this->driver->getLinkedAuthor(); if (!empty($linkedauthor)): ?>
			<? foreach($linkedauthor as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a>
			<br />
			<? endforeach; ?>
		<? endif; ?>
		
		</td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td property="creator">
		<a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a>
		<br />		
		<? $linkedcorporate = $this->driver->getLinkedCorporate(); if (!empty($linkedcorporate)): ?>
            <? foreach ($linkedcorporate as $linkcorp): ?><a href="<?=$this->record($this->driver)->getLink('author', $linkcorp)?>"><?= $this->escapeHtml($linkcorp)?>
            <br/>
            <? endforeach; ?>
        <? endif; ?>
			
		</td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>  
          <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
		<br />
		  <? $linkedauthor2 = $this->driver->getLinkedAuthor2(); if (!empty($linkedauthor2)): ?>
            <? foreach ($linkedauthor2 as $linkauthor): ?><a href="<?=$this->record($this->driver)->getLink('author', $linkauthor)?>"><?= $this->escapeHtml($linkauthor)?></a>, 
            <? endforeach; ?>
			<br />
          <? endif; ?>
		</td>
      </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>
	  
	  <? $journalholdings = $this->driver->getJournalHoldings(); if (!empty($journalholdings)): ?>
        <tr valign="top">
          <th><?=$this->transEsc('Holdings')?>: </th>
          <td><? foreach ($journalholdings as $field): ?><?= $this->escapeHtml($field)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td> 
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="place"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
		  
		  <? $linkedimprint = $this->driver->getLinkedImprint(); if (!empty($linkedimprint)): ?>
              <? foreach ($linkedimprint as $field): ?><?= $this->escapeHtml($field)?><br/>
			  <? endforeach; ?>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition">
		<?=$this->escapeHtml($edition)?>
		<br />
		
		<? $linkededition = $this->driver->getLinkedEdition(); if (!empty($linkededition)): ?>
			<? foreach($linkededition as $field): ?>
            <?=$this->escapeHtml($field)?>
			<br />
			<? endforeach; ?>
		<? endif; ?>
		
		</td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
		  
		  <? $linkedseries = $this->driver->getLinkedSeries(); if (!empty($linkedseries)): ?>
            <? foreach ($linkedseries as $linkseries): ?><a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?= $this->escapeHtml($linkseries)?></a>
               <? if (!empty($field['number'])): ?> ; <?=$this->escapeHtml($field['number'])?>
               <? endif; ?><br/>
            <? endforeach; ?>
          <? endif; ?>
		  
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>  
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
		  <? $linkedtopic = $this->driver->getLinkedTopic(); if (!empty($linkedtopic)): ?>
            <br />
			<? foreach ($linkedtopic as $linktopic): ?><a href="http://albert.lis.soas.ac.uk/Search/Results?lookfor=<?= $this->escapeHtml($linktopic)?>&type=Subject"><?= $this->escapeHtml($linktopic)?></a>
            <br />
			<? endforeach; ?>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? if (!empty($urls) || $openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
