<table class="table table-condensed">
  <tr>
    <!--<th class="hidden-xs"><?=$this->transEsc('Location')?></th>-->
    <th class="hidden-xs"><?=$this->transEsc('Call Number')?></th>
    <th class="hidden-xs"><?=$this->transEsc('Status')?></th>
  </tr>
  <? $i = 0; foreach ($this->statusItems as $item): ?>
    <? if (++$i == 5) break; // Show no more than 5 items ?>
    <tr>
      <!--<td><a href="http://www.soas.ac.uk/library/using/finding/location/"><?=$this->escapeHtml($item['location'])?></a></td>-->
      <td><a href="/Alphabrowse/Home?source=callnumber&from=<?=$this->escapeHtml($item['callnumber'])?>"><?=$this->escapeHtml($item['callnumber'])?></a></td>
      <td>
        <? if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
          <span><?=$this->transEsc("status_unknown_message")?></span>
        <? elseif ($item['availability']): ?>
          <span class="text-success"><?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc($item['status'])?></span>
        <? else: ?>
          <span class="text-danger"><?=$this->transEsc('Due')?>: <?=$this->escapeHtml($item['duedate'])?></span>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
<? if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', array('id' => $this->statusItems[0]['id']))?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more')?> ...</a></td></tr>
<? endif; ?>
</table>
